spring:
  application:
    name: profile-matcher
  # h2 config
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  # Datasource config
  datasource:
    url: jdbc:h2:mem:profile-matcher-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

#JPA config
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ## VALIDATE database schema on boot
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.changelog.yaml

application:
  campaing-http-service:
    uri: http://localhost:8080

server:
  port: 8080



