databaseChangeLog:

  - changeSet:
      id: create-matcher-table-1
      author: aherrera
      changes:
        ## Create Matcher table
        - createTable:
            tableName: matcher
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: min
                  type: INT
              - column:
                  name: max
                  type: INT
              - column:
                  name: country
                  type: VARCHAR(255)
                  constraints:
                    nullable: true
              - column:
                  name: has_items
                  type: VARCHAR(255)
              - column:
                  name: does_not_have_items 
                  type: VARCHAR(255)

  - changeSet:
      ## Create Matcher table
      id: create-campaign-table-1
      author: aherrera
      changes:
        - createTable:
            tableName: campaign
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: game
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: priority
                  type: DOUBLE
              - column:
                  ## FK with Matcher
                  name: matcher_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: start_date
                  type: TIMESTAMP 
              - column:
                  name: end_date
                  type: TIMESTAMP 
              - column:
                  name: enabled
                  type: BOOLEAN
              - column:
                  name: last_updated
                  type: TIMESTAMP 

        - addForeignKeyConstraint:
            baseTableName: campaign
            baseColumnNames: matcher_id
            referencedTableName: matcher
            referencedColumnNames: id
            constraintName: fk_campaign_matcher
            onDelete: SET NULL

  - changeSet:
      id: create-player-profile-table-1
      author: aherrera
      changes:
        - createTable:
            tableName: player_profile
            columns:
              - column:
                  name: player_id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: credential
                  type: VARCHAR(255)
              - column:
                  name: created_at
                  type: TIMESTAMP
              - column:
                  name: modified_at
                  type: TIMESTAMP
              - column:
                  name: last_session
                  type: TIMESTAMP
              - column:
                  name: total_spent
                  type: DOUBLE
              - column:
                  name: total_refund
                  type: DOUBLE
              - column:
                  name: total_transactions
                  type: INT
              - column:
                  name: last_purchase
                  type: TIMESTAMP
              - column:
                  name: inventory
                  type: VARCHAR(1024)
                  constraints:
                    nullable: true
              - column:
                  name: level
                  type: INT
              - column:
                  name: xp
                  type: INT
              - column:
                  name: total_playtime
                  type: INT
              - column:
                  name: country
                  type: VARCHAR(2)
              - column:
                  name: language
                  type: VARCHAR(10)
              - column:
                  name: birth_date
                  type: TIMESTAMP
              - column:
                  name: gender
                  type: VARCHAR(50)

              - column:
                  name: custom_field
                  type: VARCHAR(255)

              - column:
                  name: clan_id
                  type: BIGINT
                  constraints:
                    nullable: true

  - changeSet:
      id: create-device-table-1
      author: aherrera
      changes:
        - createTable:
            tableName: device
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: model
                  type: VARCHAR(255)
              - column:
                  name: carrier
                  type: VARCHAR(255)
              - column:
                  name: firmware
                  type: VARCHAR(255)
              - column:
                  name: player_id
                  type: UUID
                  constraints:
                    nullable: false

        # Add foreign key constraint from device to player_profile
        - addForeignKeyConstraint:
            baseTableName: device
            baseColumnNames: player_id
            referencedTableName: player_profile
            referencedColumnNames: player_id
            constraintName: fk_device_player_profile
            onDelete: CASCADE

  - changeSet:
      id: create-clan-table-1
      author: aherrera
      changes:
        - createTable:
            tableName: clan
            columns:
              - column:
                  name: id
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false

  # Add foreign key constraint from player_profile to clan
  - changeSet:
      id: add-fk-player-profile-clan-1
      author: aherrera
      changes:
        - addForeignKeyConstraint:
            baseTableName: player_profile
            baseColumnNames: clan_id
            referencedTableName: clan
            referencedColumnNames: id
            constraintName: fk_player_profile_clan
            onDelete: SET NULL # If clan is deleted, player's clan_id becomes NULL